import '../styles/globals.scss';
import "@rainbow-me/rainbowkit/styles.css";
import Head from 'next/head';
import type { AppProps } from 'next/app';
import { ChakraProvider } from '@chakra-ui/react';

import { 
  WagmiConfig,
  createClient,
  configureChains   
} from "wagmi";
import { 
  localhost,
  polygonMumbai 
} from "wagmi/chains";
import {
  getDefaultWallets,
  RainbowKitProvider
} from "@rainbow-me/rainbowkit";
import { publicProvider } from "wagmi/providers/public";

const { provider, chains } = configureChains(
  [polygonMumbai, localhost],
  [publicProvider()]
);

const { connectors } = getDefaultWallets({
  appName: "zkTender",
  chains
});

const wagmiClient = createClient({
  autoConnect: true,
  connectors,
  provider
});

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <WagmiConfig client={wagmiClient}>
      <RainbowKitProvider chains={chains}>
        <ChakraProvider>
          <Head>
            <title>zkTender</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Component {...pageProps} />
        </ChakraProvider>
      </RainbowKitProvider>
    </WagmiConfig>
  );
}

export default MyApp;
